version: '3'
services:
  db-zotero-mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=zotero
    volumes:
      - db_data:/var/lib/mysql
  db-zotero-elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
   environment:
     - cluster.name=zotero
     - xpack.security.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  db-zotero-redis:
     image: redis:5.0
  db-zotero-memcached:
     image: memcached:1.5
  db-zotero-localstack:
    image: atlassianlabs/localstack
    environment:
      - SERVICES=sns,sqs,apigateway
  db-zotero-minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=zotero
      - MINIO_SECRET_KEY=zoterodocker
    volumes:
      - minio_data:/data
    command: server /data
    labels:
      - "traefik.backend=zotero-s3"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:zotero-s3.speckfamily.org"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.redirect.permanent=false"
    networks:
      - web
      - default
  app-zotero:
    image: app-zotero
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../:/var/www/zotero:rw"
      - "./config/config.inc.php:/var/www/zotero/include/config/config.inc.php:ro"
      - "./config/dbconnect.inc.php:/var/www/zotero/include/config/dbconnect.inc.php:ro"
      - "./config/default.js:/var/www/zotero/stream-server/config/default.js:ro"
    environment:
      - RUN_USER=www-data
      - RUN_GROUP=www-data
    depends_on:
      - db-zotero-mysql
      - db-zotero-elasticsearch
      - db-zotero-redis
      - db-zotero-memcached 
    links:
      - db-zotero-mysql:mysql
      - db-zotero-elasticsearch:elasticsearch
      - db-zotero-redis:redis
      - db-zotero-memcached:memcached
      - db-zotero-localstack:localstack
      - db-zotero-minio:minio
    labels:
      - "traefik.zotero.backend=zotero"
      - "traefik.docker.network=web"
      - "traefik.zotero.frontend.rule=Host:zotero.speckfamily.org"
      - "traefik.enable=true"
      - "traefik.zotero.port=80"
      - "traefik.zotero.frontend.headers.STSSeconds=315360000"
      - "traefik.zotero.frontend.redirect.entryPoint=https"
      - "traefik.zotero.frontend.redirect.permanent=false"
      - "traefik.zoterostream.backend=zoterostream"
      - "traefik.zoterostream.frontend.rule=Host:zotero-stream.speckfamily.org"
      - "traefik.zoterostream.port=81"
      - "traefik.zoterostream.frontend.headers.STSSeconds=315360000"
      - "traefik.zoterostream.frontend.redirect.entryPoint=https"
      - "traefik.zoterostream.frontend.redirect.permanent=false"
    networks:
      - web
      - default
networks:
  web:
    external: true
volumes:
  db_data: {}
  minio_data: {}
